
== The Basics


Tag libraries and GSP pages can be tested with the
`grails.testing.web.taglib.TagLibUnitTest` trait.

[source,groovy]
----
include::{demoAppDir}/grails-app/taglib/demo/SampleTagLib.groovy[tags=basic_declaration;hello_world,indent=0]
----

[source,groovy]
----
include::{demoAppDir}/src/test/groovy/demo/SampleTagLibSpec.groovy[tags=basic_declaration;test_simple_tag_as_method,indent=0]
----

Adding the `TagLibUnitTest` trait to a test causes a new `tagLib` field to be
automatically created for the TagLib class under test.  The `tagLib` property can
be used to test calling tags as function calls. The return value of a function
call is either a `org.grails.buffer,StreamCharBuffer`
instance or the object returned from the tag closure when
`returnObjectForTags` feature is used.

To test a tag which accepts parameters, specify the parameter values as named
arguments to the method call.

[source,groovy]
----
include::{demoAppDir}/grails-app/taglib/demo/SampleTagLib.groovy[tags=basic_declaration;say_hello,indent=0]
----
[source,groovy]
----
include::{demoAppDir}/src/test/groovy/demo/SampleTagLibSpec.groovy[tags=basic_declaration;test_tag_as_method_with_parameters,indent=0]
----

Alternatively, tags may be tested with the `applyTemplate` method which accepts
a `String` parameter that will be evaluated as if it were source code in a GSP.

[source,groovy]
----
include::{demoAppDir}/src/test/groovy/demo/SampleTagLibSpec.groovy[tags=basic_declaration;test_simple_tag_with_applyTemplate,indent=0]
----

