name: Java CI
on:
  push:
    branches:
      - master
      - '[2-9]+.[1-9]+.x'
  pull_request:
    branches:
      - master
      - '[2-9]+.[1-9]+.x'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11']
    env:
      WORKSPACE: ${{ github.workspace }}
      GRADLE_OPTS: -Xmx1500m -Dfile.encoding=UTF-8
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Optional setup step
        run: |
          [ -f ./setup.sh ] && ./setup.sh || true
      - name: Run Tests
        run: ./gradlew classes check --no-daemon
      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Run Assemble
        if: success() && github.event_name == 'push' && matrix.java == '8'
        run: ./gradlew assemble
      - name: Publish to repo.grails.org
        if: success() && github.event_name == 'push' && matrix.java == '8'
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          ./gradlew -Dorg.gradle.internal.publish.checksums.insecure=true publish
          echo "Publishing Docs..."
          ./gradlew docs
      - name: Publish to Github Pages
        if: success() && github.event_name == 'push' && matrix.java == '8'
        uses: micronaut-projects/github-pages-deploy-action@master
        env:
          TARGET_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/docs
          COMMIT_EMAIL: behlp@objectcomputing.com
          COMMIT_NAME: Puneet Behl
